version: '3.8'
services:
  db:
    image: postgres:15
    container_name: movie-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: movie-api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_NAME: moviedb
      TMDB_API_KEY: 5a01f45ab8301d2c65d5ef66cd9649f0
      PORT: 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: npm run start

volumes:
  pgdata: